_start:
    path:  /
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:index }

user_add:
    path: /user/add
    defaults: { _controller: NetresearchTimeTrackerBundle:User:add }

time_summary:
    path: /getTimeSummary
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getTimeSummary }

interpretation_activity:
    path: /interpretation/activity
    defaults: { _controller: NetresearchTimeTrackerBundle:Interpretation:groupByActivity }

interpretation_time:
    path: /interpretation/time
    defaults: { _controller: NetresearchTimeTrackerBundle:Interpretation:groupByWorktime }

interpretation_customer:
    path: /interpretation/customer
    defaults: { _controller: NetresearchTimeTrackerBundle:Interpretation:groupByCustomer }

interpretation_project:
    path: /interpretation/project
    defaults: { _controller: NetresearchTimeTrackerBundle:Interpretation:groupByProject }

interpretation_ticket:
    path: /interpretation/ticket
    defaults: { _controller: NetresearchTimeTrackerBundle:Interpretation:groupByTicket }

interpretation_user:
    path: /interpretation/user
    defaults: { _controller: NetresearchTimeTrackerBundle:Interpretation:groupByUser }

interpretation_entries:
    path: /interpretation/entries
    defaults: { _controller: NetresearchTimeTrackerBundle:Interpretation:getLastEntries }

timetracking_save:
    path: /tracking/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Crud:save }

timetracking_delete:
    path: /tracking/delete
    defaults: { _controller: NetresearchTimeTrackerBundle:Crud:delete }

timetracking_bulkentry:
    path: /tracking/bulkentry
    defaults: { _controller: NetresearchTimeTrackerBundle:Crud:bulkentry }

_getSummary:
    path: /getSummary
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getSummary }

_getData:
    path:  /getData
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getData }

_getDataDays:
    path:  /getData/days/{days}
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getData, days: 3 }
    requirements:
        days:  \d{1,2}

_getCustomers:
    path:  /getCustomers
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getCustomers }

_getAllCustomers:
    path:  /getAllCustomers
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:getCustomers }

_getCustomer:
    path:  /getCustomer
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getCustomer }

_getAllTeams:
    path:  /getAllTeams
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:getTeams }

_getUsers:
    path:  /getUsers
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getUsers }

_getAllUsers:
    path:  /getAllUsers
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:getUsers }

_getProjects:
    path:  /getProjects
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getProjects }

_getAllProjects:
    path:  /getAllProjects
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getAllProjects }

_getActivities:
    path:  /getActivities
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getActivities }

_getTicketSystems:
    path:  /getTicketSystems
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:getTicketSystems }

_getHolidays:
    path:  /getHolidays
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getHolidays }

_getAllPresets:
    path:  /getAllPresets
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:getPresets }

_getContracts:
    path:  /getContracts
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:getContracts }

_getTicketTimeSummary:
    path: /getTicketTimeSummary/{ticket}
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getTicketTimeSummary, ticket: null }

_getTicketTimeSummaryJs:
    path: /scripts/timeSummaryForJira
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:getTicketTimeSummaryJs }

_login:
    path:  /login
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:login }

_logout:
    path:  /logout
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:logout }

_export:
    path: /export/{days}
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:export, days: 10000 }
    requirements:
        days: \d+

_controllingExport:
    path: /controlling/export/{userid}/{year}/{month}/{project}/{customer}/{billable}
    defaults:
      _controller: NetresearchTimeTrackerBundle:Controlling:export
      userid: 0
      year: 0
      month: 0
      project: 0
      customer: 0
      billable: 0
    requirements: { year: \d+, userid: \d+}

check_status:
    path: /status/check
    defaults: { _controller: NetresearchTimeTrackerBundle:Status:check }

check_page:
    path: /status/page
    defaults: { _controller: NetresearchTimeTrackerBundle:Status:page }

saveProject:
    path: /project/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:saveProject }

deleteProject:
    path: /project/delete
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:deleteProject }

syncProjectSubtickets:
    path: /projects/{project}/syncsubtickets
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:syncProjectSubtickets }

saveCustomer:
    path: /customer/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:saveCustomer }

deleteCustomer:
    path: /customer/delete
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:deleteCustomer }

saveUser:
    path: /user/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:saveUser }

deleteUser:
    path: /user/delete
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:deleteUser }

savePreset:
    path: /preset/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:savePreset }

saveTicketSystem:
    path: /ticketsystem/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:saveTicketSystem }

deleteTicketSystem:
    path: /ticketsystem/delete
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:deleteTicketSystem }

deletePreset:
    path: /preset/delete
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:deletePreset }

saveSettings:
    path: /settings/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Settings:save }

saveActivity:
    path: /activity/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:saveActivity }

deleteActivity:
    path: /activity/delete
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:deleteActivity }

saveTeam:
    path: /team/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:saveTeam }

deleteTeam:
    path: /team/delete
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:deleteTeam }

saveContract:
    path: /contract/save
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:saveContract }

deleteContract:
    path: /contract/delete
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:deleteContract }

jiraOAuthCallback:
    path: /jiraoauthcallback
    defaults: { _controller: NetresearchTimeTrackerBundle:Default:jiraOAuthCallback }

syncEntriesToJira:
    path: /syncentries/jira
    defaults: { _controller: NetresearchTimeTrackerBundle:Admin:jiraSyncEntries }
